# backend/app/timeline_suggestions/next_step_rules.py

"""
Rule-based next-step suggestion engine — deliberately NOT machine learning,
per the project brief ("rule-based only").

Trimmed to match Anwesha's ACTUAL trained model (confirmed via
ml_models/yolo/dataset.yaml):

    names:
      0: knife
      1: backpack

This is a custom 2-class fine-tuned model, NOT stock COCO — so only
"knife" and "backpack" will ever appear as class names. Rules for other
object types have been removed; add them back only if the model is
retrained with more classes.

Reads from Evidence.extra_metadata as actually stored (confirmed via
sample_case.json):

    "extra_metadata": {
        "yolo_detections": ["crowbar", "cash_register"],
        "nlp_entities": {"names": [...], "locations": [...], "time_mentions": [...]}
    }

NOTE: sample_case.json's own example includes "crowbar" and "cash_register"
— neither of which exist in the 2-class knife/backpack model. That mismatch
is worth flagging to the team: either the sample data is aspirational/not
generated by the real model, or the model is expected to grow more classes
later. Rules below match strictly against the *current* trained classes.
"""

from app.shared.exceptions import InsufficientDataError


# ---------------------------------------------------------------------------
# Rule table — object class (from Anwesha's 2-class YOLO model) -> suggestion
# ---------------------------------------------------------------------------

OBJECT_SUGGESTION_RULES = {
    "knife": "A knife was detected in the evidence. Suggest documenting it as physical evidence and checking for nearby CCTV coverage.",
    "backpack": "A bag was detected in the frame. Suggest checking if it was recovered or left at the scene.",
}

# Evidence-type gap rules — "if X was detected but Y evidence type doesn't
# exist yet for this case, suggest collecting Y."
EVIDENCE_GAP_RULES = [
    {
        "trigger_objects": {"knife"},
        "missing_evidence_type": "cctv_frame",
        "suggestion": "A potential weapon was detected but no CCTV footage has been uploaded for this case yet. Suggest checking nearby CCTV.",
    },
    {
        "trigger_objects": {"knife", "backpack"},
        "missing_evidence_type": "witness_statement",
        "suggestion": "Physical evidence was detected but no witness statement exists yet. Suggest following up for a statement.",
    },
]


def generate_suggestions(evidence_list: list, existing_evidence_types: list[str] | None = None) -> list[str]:
    """
    Takes a case's list of evidence (ORM objects or dicts, same shape as
    timeline_builder.build_timeline expects) and returns plain-language
    next-step suggestions.

    If existing_evidence_types isn't passed explicitly, it's derived from
    the evidence_list itself.
    """
    if not evidence_list:
        raise InsufficientDataError("No evidence available to generate suggestions.")

    detected_classes: set[str] = set()
    derived_types: set[str] = set()

    for evidence in evidence_list:
        if isinstance(evidence, dict):
            metadata = evidence.get("extra_metadata", {}) or {}
            evidence_type = evidence.get("evidence_type")
        else:
            metadata = evidence.extra_metadata or {}
            evidence_type = evidence.evidence_type.value if hasattr(evidence.evidence_type, "value") else evidence.evidence_type

        detected_classes.update(metadata.get("yolo_detections", []))
        if evidence_type:
            derived_types.add(evidence_type)

    existing_evidence_types = set(existing_evidence_types) if existing_evidence_types else derived_types

    suggestions: list[str] = []

    for class_name in detected_classes:
        if class_name in OBJECT_SUGGESTION_RULES:
            suggestions.append(OBJECT_SUGGESTION_RULES[class_name])

    for rule in EVIDENCE_GAP_RULES:
        objects_present = rule["trigger_objects"] & detected_classes
        evidence_missing = rule["missing_evidence_type"] not in existing_evidence_types
        if objects_present and evidence_missing:
            suggestions.append(rule["suggestion"])

    if not suggestions:
        suggestions.append("No specific next steps triggered by this evidence. Manual review recommended.")

    return suggestions
